name: ghost_mark
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.2
  flutter_markdown_plus: ^1.0.0+1
  flutter_native_splash: ^2.4.4
  gpt_markdown: ^1.0.9
  hooks_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  riverpod_generator: ^2.6.3
  build_runner: ^2.4.13
  custom_lint: ^0.7.0
  riverpod_lint: ^2.6.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/text-logo.png

flutter_native_splash:
  android: true
  ios: true
  web: false
  color: "#ffffff"
  image: assets/images/splash-logo.png
  android_12:
    color: "#ffffff"
    image: assets/images/splash-logo.png